version: "3.7"

services:
  golang-exercise:
    container_name: "exercise"
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../code:/build
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    restart: unless-stopped