// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: exchangerate.proto

package exchangeratepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeRateService_FetchRate_FullMethodName = "/exchangerate.ExchangeRateService/fetchRate"
)

// ExchangeRateServiceClient is the client API for ExchangeRateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeRateServiceClient interface {
	FetchRate(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error)
}

type exchangeRateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeRateServiceClient(cc grpc.ClientConnInterface) ExchangeRateServiceClient {
	return &exchangeRateServiceClient{cc}
}

func (c *exchangeRateServiceClient) FetchRate(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyResponse)
	err := c.cc.Invoke(ctx, ExchangeRateService_FetchRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeRateServiceServer is the server API for ExchangeRateService service.
// All implementations must embed UnimplementedExchangeRateServiceServer
// for forward compatibility.
type ExchangeRateServiceServer interface {
	FetchRate(context.Context, *CurrencyRequest) (*CurrencyResponse, error)
	mustEmbedUnimplementedExchangeRateServiceServer()
}

// UnimplementedExchangeRateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeRateServiceServer struct{}

func (UnimplementedExchangeRateServiceServer) FetchRate(context.Context, *CurrencyRequest) (*CurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRate not implemented")
}
func (UnimplementedExchangeRateServiceServer) mustEmbedUnimplementedExchangeRateServiceServer() {}
func (UnimplementedExchangeRateServiceServer) testEmbeddedByValue()                             {}

// UnsafeExchangeRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeRateServiceServer will
// result in compilation errors.
type UnsafeExchangeRateServiceServer interface {
	mustEmbedUnimplementedExchangeRateServiceServer()
}

func RegisterExchangeRateServiceServer(s grpc.ServiceRegistrar, srv ExchangeRateServiceServer) {
	// If the following call pancis, it indicates UnimplementedExchangeRateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeRateService_ServiceDesc, srv)
}

func _ExchangeRateService_FetchRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeRateServiceServer).FetchRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeRateService_FetchRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeRateServiceServer).FetchRate(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeRateService_ServiceDesc is the grpc.ServiceDesc for ExchangeRateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeRateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchangerate.ExchangeRateService",
	HandlerType: (*ExchangeRateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetchRate",
			Handler:    _ExchangeRateService_FetchRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchangerate.proto",
}
